---
name: Crypt-FNA-Async
version: 0.02
author:
  - 'Mario Rossano aka Anak <software@netlogicalab.com>'
abstract: Crypt::FNA::Async allow parallel encryption/decryption with Crypt::FNA
license: perl
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Crypt::FNA::Async:
    file: lib/Crypt/FNA/Async.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
